language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
script:
  - "sbt +clean +coverage +test +it:test"
after_success:
  - "sbt coverageReport"
  - "sbt codacyCoverage"
  - "bash <(curl -s https://codecov.io/bash)"
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sbt
  - $HOME/.ivy2
